<?php
/**
 * Email Configuration Setup Wizard
 * This script helps you configure email settings for OTP functionality
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$config_file = __DIR__ . '/config/email_config.php';
$test_mode = isset($_GET['test']) || (php_sapi_name() === 'cli' && isset($argv[1]) && $argv[1] === 'test');

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Setup Wizard - KPRCAS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }
        .wizard-container { max-width: 800px; margin: 0 auto; background: white; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.3); }
        .wizard-header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 15px 15px 0 0; text-align: center; }
        .wizard-content { padding: 40px; }
        .step { display: none; }
        .step.active { display: block; }
        .alert-custom { padding: 20px; border-radius: 10px; margin: 20px 0; border-left: 5px solid; }
        .alert-info-custom { background: #e3f2fd; border-color: #2196f3; color: #0d47a1; }
        .alert-success-custom { background: #e8f5e9; border-color: #4caf50; color: #1b5e20; }
        .alert-warning-custom { background: #fff3e0; border-color: #ff9800; color: #e65100; }
        .alert-danger-custom { background: #ffebee; border-color: #f44336; color: #b71c1c; }
        .btn-primary-custom { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border: none; padding: 12px 30px; border-radius: 10px; font-weight: 600; }
        .btn-primary-custom:hover { transform: translateY(-2px); box-shadow: 0 5px 15px rgba(0,0,0,0.2); }
        code { background: #f5f5f5; padding: 2px 8px; border-radius: 4px; color: #d63384; font-size: 90%; }
        .instructions { background: #f8f9fa; padding: 20px; border-radius: 10px; margin: 20px 0; }
        .instructions ol { padding-left: 20px; }
        .instructions li { margin: 10px 0; }
        pre { background: #2d2d2d; color: #f8f8f2; padding: 15px; border-radius: 8px; overflow-x: auto; }
        .form-control { border: 2px solid #e9ecef; border-radius: 8px; padding: 12px; }
        .form-control:focus { border-color: #667eea; box-shadow: 0 0 0 0.2rem rgba(102,126,234,0.25); }
    </style>
</head>
<body>
    <div class="wizard-container">
        <div class="wizard-header">
            <h1><i class="fas fa-envelope-open-text"></i> Email Setup Wizard</h1>
            <p>Configure SMTP settings for OTP email functionality</p>
        </div>
        
        <div class="wizard-content">
            <!-- Step 1: Welcome & Requirements -->
            <div class="step active" id="step1">
                <h2><i class="fas fa-info-circle text-primary"></i> Welcome</h2>
                <p>This wizard will help you configure email settings for the KPRCAS Attendance System's OTP functionality.</p>
                
                <div class="alert-info-custom">
                    <h5><i class="fas fa-exclamation-triangle"></i> Current Status</h5>
                    <p><strong>OTP emails are NOT working</strong> because SMTP credentials are not configured.</p>
                    <p>You need a Gmail account with an App Password to send OTP emails.</p>
                </div>
                
                <div class="instructions">
                    <h5>What you'll need:</h5>
                    <ol>
                        <li><strong>Gmail Account</strong> - Any Gmail address (@gmail.com)</li>
                        <li><strong>2-Step Verification</strong> - Must be enabled on your Google Account</li>
                        <li><strong>App Password</strong> - A 16-character password generated by Google</li>
                    </ol>
                </div>
                
                <div class="alert-warning-custom">
                    <h5><i class="fas fa-shield-alt"></i> Security Note</h5>
                    <p>We recommend creating a dedicated Gmail account for this system rather than using your personal email.</p>
                </div>
                
                <button class="btn btn-primary btn-primary-custom" onclick="showStep(2)">
                    Next: Get App Password <i class="fas fa-arrow-right"></i>
                </button>
            </div>
            
            <!-- Step 2: Gmail App Password Instructions -->
            <div class="step" id="step2">
                <h2><i class="fas fa-key text-warning"></i> Get Gmail App Password</h2>
                
                <div class="instructions">
                    <h5>Step-by-step instructions:</h5>
                    <ol>
                        <li>
                            <strong>Enable 2-Step Verification</strong>
                            <ul>
                                <li>Go to: <a href="https://myaccount.google.com/security" target="_blank">Google Account Security</a></li>
                                <li>Under "How you sign in to Google", click "2-Step Verification"</li>
                                <li>Follow the steps to enable it (if not already enabled)</li>
                            </ul>
                        </li>
                        <li>
                            <strong>Create App Password</strong>
                            <ul>
                                <li>Go to: <a href="https://myaccount.google.com/apppasswords" target="_blank">App Passwords</a></li>
                                <li>Select app: <code>Mail</code></li>
                                <li>Select device: <code>Other (Custom name)</code></li>
                                <li>Enter name: <code>KPRCAS Attendance</code></li>
                                <li>Click "Generate"</li>
                            </ul>
                        </li>
                        <li>
                            <strong>Copy the App Password</strong>
                            <ul>
                                <li>Google will show a 16-character password (like: <code>abcd efgh ijkl mnop</code>)</li>
                                <li>Copy this password (remove spaces)</li>
                                <li>Keep it safe - you'll need it in the next step</li>
                            </ul>
                        </li>
                    </ol>
                </div>
                
                <div class="alert-warning-custom">
                    <h5><i class="fas fa-exclamation-circle"></i> Important</h5>
                    <ul>
                        <li>The App Password is <strong>different</strong> from your regular Gmail password</li>
                        <li>It's a 16-character code like: <code>abcdefghijklmnop</code></li>
                        <li>You won't be able to see it again, so copy it now</li>
                    </ul>
                </div>
                
                <button class="btn btn-secondary" onclick="showStep(1)">
                    <i class="fas fa-arrow-left"></i> Back
                </button>
                <button class="btn btn-primary btn-primary-custom" onclick="showStep(3)">
                    Next: Configure Settings <i class="fas fa-arrow-right"></i>
                </button>
            </div>
            
            <!-- Step 3: Configuration Form -->
            <div class="step" id="step3">
                <h2><i class="fas fa-cog text-success"></i> Configure SMTP Settings</h2>
                
                <form id="configForm" method="POST" action="save_email_config.php">
                    <div class="mb-3">
                        <label for="smtp_username" class="form-label">
                            <i class="fas fa-envelope"></i> Gmail Address
                        </label>
                        <input type="email" class="form-control" id="smtp_username" name="smtp_username" 
                               placeholder="your-email@gmail.com" required>
                        <small class="text-muted">Your full Gmail address</small>
                    </div>
                    
                    <div class="mb-3">
                        <label for="smtp_password" class="form-label">
                            <i class="fas fa-key"></i> Gmail App Password
                        </label>
                        <input type="text" class="form-control" id="smtp_password" name="smtp_password" 
                               placeholder="abcdefghijklmnop" required pattern="[a-zA-Z]{16}" maxlength="16">
                        <small class="text-muted">16-character app password (no spaces)</small>
                    </div>
                    
                    <div class="mb-3">
                        <label for="smtp_from_email" class="form-label">
                            <i class="fas fa-paper-plane"></i> From Email (for OTP emails)
                        </label>
                        <input type="email" class="form-control" id="smtp_from_email" name="smtp_from_email" 
                               value="noreply@kprcas.ac.in" required>
                        <small class="text-muted">This appears as the sender in OTP emails</small>
                    </div>
                    
                    <div class="alert-info-custom">
                        <h5><i class="fas fa-info-circle"></i> SMTP Settings</h5>
                        <p>The following settings will be used:</p>
                        <ul>
                            <li><strong>Host:</strong> smtp.gmail.com</li>
                            <li><strong>Port:</strong> 587 (TLS/STARTTLS)</li>
                            <li><strong>Authentication:</strong> Enabled</li>
                        </ul>
                    </div>
                    
                    <button type="button" class="btn btn-secondary" onclick="showStep(2)">
                        <i class="fas fa-arrow-left"></i> Back
                    </button>
                    <button type="button" class="btn btn-primary btn-primary-custom" onclick="testConfig()">
                        <i class="fas fa-vial"></i> Test & Save Configuration
                    </button>
                </form>
                
                <div id="testResult" class="mt-4" style="display: none;"></div>
            </div>
            
            <!-- Step 4: Success -->
            <div class="step" id="step4">
                <div class="alert-success-custom">
                    <h2><i class="fas fa-check-circle"></i> Configuration Saved!</h2>
                    <p>Your email settings have been configured successfully.</p>
                </div>
                
                <div class="instructions">
                    <h5>What's next?</h5>
                    <ol>
                        <li>Go to the <a href="login.php">Login Page</a></li>
                        <li>Click on the "Student" tab</li>
                        <li>Enter a student email address</li>
                        <li>Click "Send OTP"</li>
                        <li>Check your email for the OTP code</li>
                    </ol>
                </div>
                
                <div class="alert-info-custom">
                    <h5><i class="fas fa-terminal"></i> Manual Testing</h5>
                    <p>You can also test email sending from the command line:</p>
                    <pre>php login/phpmailer_smtp_test.php your-test-email@example.com</pre>
                </div>
                
                <a href="login.php" class="btn btn-primary btn-primary-custom">
                    <i class="fas fa-sign-in-alt"></i> Go to Login Page
                </a>
                <a href="email_setup.php" class="btn btn-secondary">
                    <i class="fas fa-redo"></i> Reconfigure
                </a>
            </div>
        </div>
    </div>
    
    <script>
        function showStep(stepNum) {
            document.querySelectorAll('.step').forEach(el => el.classList.remove('active'));
            document.getElementById('step' + stepNum).classList.add('active');
        }
        
        function testConfig() {
            const resultDiv = document.getElementById('testResult');
            resultDiv.style.display = 'block';
            resultDiv.innerHTML = '<div class="alert-info-custom"><i class="fas fa-spinner fa-spin"></i> Testing SMTP connection...</div>';
            
            const formData = new FormData(document.getElementById('configForm'));
            
            fetch('save_email_config.php', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    resultDiv.innerHTML = '<div class="alert-success-custom"><i class="fas fa-check-circle"></i> ' + data.message + '</div>';
                    setTimeout(() => showStep(4), 2000);
                } else {
                    resultDiv.innerHTML = '<div class="alert-danger-custom"><i class="fas fa-exclamation-circle"></i> ' + data.message + '<br><small>' + (data.error || '') + '</small></div>';
                }
            })
            .catch(error => {
                resultDiv.innerHTML = '<div class="alert-danger-custom"><i class="fas fa-exclamation-circle"></i> Error: ' + error.message + '</div>';
            });
        }
    </script>
</body>
</html>
