<?php
/**
 * Save and test email configuration
 */

header('Content-Type: application/json');
error_reporting(E_ALL);
ini_set('display_errors', 0);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Invalid request method']);
    exit;
}

$smtp_username = trim($_POST['smtp_username'] ?? '');
$smtp_password = trim($_POST['smtp_password'] ?? '');
$smtp_from_email = trim($_POST['smtp_from_email'] ?? 'noreply@kprcas.ac.in');

// Validate inputs
if (empty($smtp_username) || !filter_var($smtp_username, FILTER_VALIDATE_EMAIL)) {
    echo json_encode(['success' => false, 'message' => 'Invalid Gmail address']);
    exit;
}

if (empty($smtp_password) || strlen($smtp_password) !== 16) {
    echo json_encode(['success' => false, 'message' => 'App password must be exactly 16 characters']);
    exit;
}

// Test SMTP connection first
require_once __DIR__ . '/../vendor/autoload.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer(true);

try {
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = $smtp_username;
    $mail->Password = $smtp_password;
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port = 587;
    $mail->Timeout = 10;
    
    // Test connection without sending
    $mail->SMTPDebug = 0;
    $mail->setFrom($smtp_from_email, 'KPRCAS Attendance System');
    $mail->addAddress($smtp_username); // Send test to self
    $mail->Subject = 'KPRCAS Email Configuration Test';
    $mail->Body = 'Congratulations! Your email configuration is working correctly.';
    
    $mail->send();
    
    // If successful, save configuration
    $config_content = "<?php
// ============================================
// Email Configuration for sending OTP
// ============================================
// 
// This file was auto-generated by the Email Setup Wizard
// Last updated: " . date('Y-m-d H:i:s') . "
//
// To reconfigure: Open http://localhost/attendance/login/email_setup.php
// To test: Run command: php login/phpmailer_smtp_test.php
//
// ============================================

define('SMTP_HOST', 'smtp.gmail.com');
define('SMTP_PORT', 587);
define('SMTP_USERNAME', '" . addslashes($smtp_username) . "');
define('SMTP_PASSWORD', '" . addslashes($smtp_password) . "');
define('SMTP_FROM_EMAIL', '" . addslashes($smtp_from_email) . "');
define('SMTP_FROM_NAME', 'KPRCAS Attendance System');

// OTP Settings
define('OTP_LENGTH', 6);
define('OTP_EXPIRY_MINUTES', 10);
?>";

    $config_file = __DIR__ . '/config/email_config.php';
    if (file_put_contents($config_file, $config_content)) {
        echo json_encode([
            'success' => true,
            'message' => 'Configuration saved and tested successfully! A test email was sent to ' . $smtp_username
        ]);
    } else {
        echo json_encode([
            'success' => false,
            'message' => 'SMTP test passed but failed to save configuration file. Check file permissions.'
        ]);
    }
    
} catch (Exception $e) {
    echo json_encode([
        'success' => false,
        'message' => 'SMTP connection failed. Please check your credentials.',
        'error' => $mail->ErrorInfo
    ]);
}
?>
